[package]
name = "wgpu-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.24.1"
egui-wgpu = "0.24.1"
egui-winit = "0.24.1"
egui_demo_lib = "0.24.1"
futures = "0.3.28"
raw-window-handle = "0.6.0"
rosu-pp = "0.10.0"
tracy-client = { version = "0.16.5", default-features = false }
wgpu = "0.18.0"
winit = { version = "0.28.7" }
