[package]
name = "wgpu-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.14.0", features = ["zeroable_maybe_uninit", "zeroable_atomics"] }
egui = "0.24.1"
cgmath = { git = "https://github.com/rustgd/cgmath.git", features = ["bytemuck"] }
egui-wgpu = "0.24.1"
egui-winit = "0.24.1"
egui_demo_lib = "0.24.1"
futures = "0.3.28"
image = "0.24.7"
raw-window-handle = "0.6.0"
rosu-pp = "0.10.0"
tracy-client = { version = "0.16.5", default-features = true }
ultraviolet = { version = "0.9.2", features = ["bytemuck"] }
rosu-map = { git = "https://github.com/MaxOhn/rosu-map.git" }
wgpu = "0.18.0"
winit = { version = "0.28.7", default-features = false, feautres = ["x11"] }
smallvec = "1.13.2"
