[package]
name = "wgpu-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7"
bytemuck = { version = "1.14.0", features = ["zeroable_maybe_uninit", "zeroable_atomics"] }
cgmath = { git = "https://github.com/rustgd/cgmath.git", features = ["bytemuck"] }
egui_demo_lib = "0.24.1"
futures = "0.3.28"
image = "0.24.7"
rosu-pp = "0.10.0"
tracy-client = { version = "0.16.5", default-features = false }
ultraviolet = { version = "0.9.2", features = ["bytemuck"] }
rosu-map = { git = "https://github.com/MaxOhn/rosu-map.git" }
smallvec = "1.13.2"
rodio = "0.19.0"
egui-wgpu = "0.28.1"
wgpu = "0.20.0"
egui-winit = "0.28.1"
winit = { version = "0.29.4", default-features = false, feautres = ["x11"] }
egui = "0.28.1"
raw-window-handle = "0.6.2"
egui_file = "0.18.0"
rust-ini = "0.21.0"
thiserror = "1.0.63"
rusqlite = "0.32.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
egui_extras = "0.28.1"
r2d2_sqlite = "0.25.0"
r2d2 = "0.8.10"
rand = "0.8.5"
oneshot = { version = "0.1.8", default-features = false, features = ["std"] }
